- id: license-header
  name: License Header
  description: Add or update license headers in source files
  entry: license-header-hook
  language: python
  files: \.(py|js|ts|java|c|cpp|h|hpp|go|rs|v|vhdl|sv|vhd)$
  args: [
    "--template", "license-header.txt",
    "--copyright-holder", "Your Company LLC"
  ]
