- id: license-header
  name: License Header
  description: Add or update license headers in source files
  entry: python license_header_hook.py
  language: python
  files: \.(py|js|ts|java|c|cpp|h|hpp|go|rs)$
  args: [
    "--template", "license-header.txt",
    "--copyright-holder", "Your Company LLC"
  ]
